spring:
  application:
    name: imageStorage-dirCreation
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/Blogging_Service
    username: root
    password: Samarth95360@
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8085

#spring.datasource.url = jdbc:mysql://localhost:3306/image_indirect_try_dir
#spring.datasource.username = springstudent
#spring.datasource.password = springstudent


# Set maximum file size to 100 MB
#spring.servlet.multipart.max-file-size=100MB
## Set maximum request size (including all files) to 100 MB
#spring.servlet.multipart.max-request-size=100MB

user-dir:
  base-path: E:/New folder/Spring Boot Data And Files/imageStorage+dirCreation/imageStorage-dirCreation/src/main/resources/static/images/