spring:
  application:
    name: Blogging
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 25
    username: www.samarthagarwal95360@gmail.com
    password: mxpl wrme qwdw ljus
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090




